### ISSUE TITLE
[2614] Strassenbaulinie weist Geometriefehler auf

### ISSUE THREAD

**Issue by edigonzales** [bjdarp/nplso-nf#1]
### OID
f8a3dcbd-f116-4edf-98b6-db6d7d51a70d

### Mangel 
Die Geometrie der Strassenbaulinie weist Fehler auf. Siehe Fotos.
![Screenshot 2019-10-16 at 14 16 05](https://user-images.githubusercontent.com/2767800/66919790-4d6c2c80-f022-11e9-9563-fa1489e2a4dd.png)
![Screenshot 2019-10-16 at 14 14 22](https://user-images.githubusercontent.com/2767800/66919803-5230e080-f022-11e9-9b54-c889bd90360b.png)

### Aktion
Geometriefehler bereinigen.

**Comment by edigonzales** [comment]
Tatsächlich ein Fehler. Muss bereinigt werden durch Büro.

**Comment by seraina-silberschmidt** [comment]
Task erledigt / Datensatz am 28.01.2021 via Email ans ARP abgegeben

**Comment by seraina-silberschmidt** [comment]
Kann aus meiner Sicht ebenfalls geschlossen werden (gehört zu Büsserach)
