### ISSUE TITLE
[2457] Messen LerchWeber

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#12]
[2457.log](https://github.com/bjdarp/nplso-nf/files/3754071/2457.log)
Daten wurden durch den "neuen strengeren" Validator geprüft. https://geo.so.ch/ilivalidator-nplso

### Error des Logfiles beheben:
- OID Verknüpft die nicht sein sollten.
- doppelte koordinaten
- Perimeter ist mit keinem Dokument verknüpft
- Verbindlichkeit ist nicht identisch zum Objektkatalog
- Fehlendes Attribut
- Lärmempfindlichkeit deckt nicht die ganze Gemeinde

### Inhaltliche Anpassungen
- Unterscheidung der Wohnzonen (W2a/ W2b) ist nicht möglich. Beide Typen heissen "Wohnzone", die Abkürzung "W2a". Anpassen des Typs.
- Kantonale Baulinien entlang der gesamten Kantonsstrasse erfassen.
- Link zu den Sonderbauvorschriften Rainacker in Oberramsern funktioniert nicht
- zu grosse Empfindlichkeitsklasse unterteilen

### Dokument wurde nicht gefunden
- 024_BR und 024_ZR sind vorhanden
- 020_BZR vorhanden

**Comment by adis-LW** [comment]
>     * Perimeter ist mit keinem Dokument verknüpft
Hierbei geht es wohl um Typ_Ueberlagernd_Flaeche (N527, N690, N699, N820) welche mit keinem Dokument verknüpft sind - und auch nicht sein sollten. Muss der Validator angepasst werden?

**Comment by edigonzales** [comment]
Wenn dieses Typen in den ÖREB-Kataster gehören, müssen sie mit einem Dokument verknüpft sein. Gemäss meinem Datenumbau gehören sie in den ÖREB-Kataster:

https://github.com/sogis/oereb-gretljobs/blob/master/oereb_nutzungsplanung/insert_oereb_landuseplans_tables.sql#L184
https://github.com/sogis/oereb-gretljobs/blob/master/oereb_nutzungsplanung/insert_oereb_landuseplans_tables.sql#L317

**Comment by adis-LW** [comment]
@ruff-kid Somit werden Dokumente benötigt für:

- Typ 'N527_kantonale_Uferschutzzone' (Typ_Ueberlagernd_Flaeche)
- Typ 'N690_kantonales_Vorranggebiet_Natur_und_Landschaft' (Typ_Ueberlagernd_Flaeche)
- Typ 'N699_weitere_flaechenbezogene_Festlegungen_NP' (Typ_Ueberlagernd_Flaeche)
- Typ 'N820_kantonal_geschuetztes_Kulturobjekt' (Typ_Ueberlagernd_Punkt)

**Comment by ruff-kid** [comment]
- 527 kant. Uferschutzzone - wegleitend: es gibt kein kantonaler Datensatz. Daten sind zu erheben, besitzen keine Dokumente 

- 690 kant. Vorranggebiet: nicht erfassen, kantonaler Datensatz. Master im Richtplan. Aus Sicht Nutzungsplanung keine Beschränkung und darum kein ÖREB-Thema (diese Diskusion gab es bereits zwischen Stephan und Stefan. Habe diese Fragestellung nun Sacha Peter weitergegeben zwecks Klärung)

- 699 weitere Festlegungen: Sammelbecken, deshalb allgemeingültige Regelung möglich. Archeologische Fundstelle muss erfasst werden, da es kein öffentlich zugänglichen Datensatz gibt. Darum kant. Daten erfassen - gibt keine Dokumente (welche wären zu erfassen?)

- 820 kant. geschütztes Kulturobjekt: (siehe Bemerkung im Objektkatalog: Durch die Gemeinde gestützt auf amtliche Vermessung zu erfassen;  Datensatz wird bis auf Weiteres nicht vom Kanton zur Verfügung gestellt; bestehendes Inventar mit Objektblättern soll verfügbar geemacht werden (ADA) - haben keine Dokumente dazu

**Comment by Luescher** [comment]
•527 kant. Uferschutzzone und 690 kant. Vorranggebiet - gemäss juristischen Abklärungen (Bernardo und Schläfli) sind das ÖREB.  d.h. es muss eigentlich ein Beschluss geben. 

•699 weitere Festlegungen: Nur wenn sie Nutzungsplanungsfestlegend sind braucht es ein Dokument. Validator muss angepasst werden.

•820 kant. geschütztes Kulturobjekt kommt vom ADA das ist richtig. Validator muss beim Punkobjekt noch angepasst werden. Siehe Isssue https://github.com/edigonzales/ilivalidator-web-service-nplso/issues/1#issuecomment-548258834

**Comment by edigonzales** [comment]
fixed: https://github.com/edigonzales/ilivalidator-web-service-nplso/commit/a7308d1055b1d3d0efb138ea10a08c3b47728fc9 https://github.com/edigonzales/ilivalidator-web-service-nplso/commit/5354be5db41488b6a0de8a527b177c519f16e173

**Comment by edigonzales** [comment]
In der Test-Umgebung https://geo-t.so.ch/ilivalidator-nplso sollten die Fehler behoben sein. Auf Produktionsumgebung sollte der neue Release innerhalb eines Tages verfügbar sein.

**Comment by adis-LW** [comment]
Funktioniert! Zwischenstand mit https://geo-t.so.ch/ilivalidator-nplso :
[exp1_nplmes2_20191031A.log](https://github.com/bjdarp/nplso-nf/files/3793819/exp1_nplmes2_20191031A.log)

-> warte also noch auf die Beschlüsse für 527 kant. Uferschutzzone und 690 kant. Vorranggebiet

**Comment by ruff-kid** [comment]
- 527 kant. Uferschutzzone: ist eine aussterbende Klasse. Alle gesetzlichen Grundlagen wurden aufgehoben. Darum direkt mit dem Richtplantext verknüpfen unter "200-Kanton/Richtplan/L-2_2.pdf"

- 690 kant. Vorranggebiet: löschen, kantonale Daten werden grundsätzlich nicht von den Gemeinden erhoben. Dieser Datensatz wird direkt vom Datenursprung (Richtplan) in der Nutzungsplanung dargestellt.

**Comment by adis-LW** [comment]
[20191107_Messen.zip](https://github.com/bjdarp/nplso-nf/files/3819455/20191107_Messen.zip)
... validation done: alle Mängel behoben und inhaltliche Anpassungen ergänzt/korrigiert

**Comment by ruff-kid** [comment]
@edigonzales 
kannst du die neue Version importieren und testen ob es den technischen Anforderungen genügt?

**Comment by edigonzales** [comment]
@ruff-kid Gibt es noch Dinge, die nicht vom Validator geprüft werden? (und von momentaner Relevanz sind?) 
Reich der "normale" Import?

**Comment by ruff-kid** [comment]
fertig und aufgeschaltet
