### ISSUE TITLE
[2502] Wisen LerchWeber

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#20]
Datei anpassen damit auch Version ilivalidator-1.11.3 fehlerfrei durchläuft https://geo.so.ch/ilivalidator

Bitte xtf und log-file direkt ins Github anhängen.
Wenn beendet bitte den Projects status von "Bearbeitung (Planer)" zu "Validation (ARP)" anpassen.

Um die Daten nachzuführen sind folgende Schritte zwingend einzuhalten:

- Aktuelle Daten vom Kanton herunterladen und importieren
- Daten anpassen gemäss Meldung vom Amt für Raumplanung
- Daten exportieren (INTERLIS)

**Comment by ghost** [comment]
Wisen durchläuft jetzt den ilivalidator.

[exp1_nplwis2_20200529Z.zip](https://github.com/bjdarp/nplso-nf/files/4702650/exp1_nplwis2_20200529Z.zip)

**Comment by ghost** [comment]
Das ging eigenlich ganz gut vonstatten.

**Comment by bjsvwcur** [comment]
@ruff-kid Daten sind nachgeführt
