### ISSUE TITLE
[2614] Büsserach Jermann

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#22]
Datei anpassen damit auch Version ilivalidator-1.11.3 fehlerfrei durchläuft https://geo.so.ch/ilivalidator

Bitte xtf und log-file direkt ins Github anhängen.
Wenn beendet bitte den Projects status von "Bearbeitung (Planer)" zu "Validation (ARP)" anpassen.

Um die Daten nachzuführen sind folgende Schritte zwingen einzuhalten:

- Aktuelle Daten vom Kanton herunterladen und importieren
- Daten anpassen gemäss Meldung vom Amt für Raumplanung
- Daten exportieren (INTERLIS)

**Comment by ruff-kid** [comment]
Bitte in diesem Ticket auch #1 beheben

**Comment by seraina-silberschmidt** [comment]
Hallo Thomas

Bei den Daten zur Gemeinde Büsserach ist mir aufgefallen, dass die Pläne zur Passwangstrasse nicht hinterlegt sind.
https://geoweb.so.ch/zonenplaene/Zonenplaene_pdf/124-Buesserach/Plaene/124-32-P.pdf
https://geoweb.so.ch/zonenplaene/Zonenplaene_pdf/124-Buesserach/Plaene/124-37-P.pdf
https://geoweb.so.ch/zonenplaene/Zonenplaene_pdf/124-Buesserach/Plaene/124-38-P.pdf 
 Mal schauen ob das Amt für Verkehr und Tiefbau reklamiert... 

Freudl. Grüsse, Stephan

**Comment by seraina-silberschmidt** [comment]
In Büsserach gibt es insgesamt 14 rechtsgültige kantonale Erschliessungspläne (darunter die 3, welche Stephan Schader erwähnt). Bei der Digitalisierung haben wir nur jene erfasst, welche jünger sind als der Strassenkategorienplan, also 2. 
Das ARP hat die fehlenden Perimeter bei der Datenprüfung nicht bemängelt. In unserem Übersichtsdokument waren diese Pläne unter «nicht erfasste Pläne» aufgeführt. 

Für die korrekte (Nach-)Erfassung der 12 fehlenden kantonalen Erschliessungspläne wären folgende Schritte nötig:
•	Einpassen der Pläne im ArcMap
•	Im Topic Nutzungsplanung: Erfassen der Perimeter als überlagernde Flächen inkl. den jeweiligen Typ-Einträgen
•	In der Dokumententabelle: Erfassung der Pläne und Verknüpfung mit den Typ-Einträgen der überlagernden Flächen
•	Im Topic Erschliessung: Abtrennung der jeweiligen Strassenflächen (Erstellung separater Geometrien), Erstellung neuer Typ-Einträge, Verlinkung der Typ-Einträge mit den jeweiligen kantonalen Erschliessungsplänen.

Den Aufwand für diese Arbeiten schätze ich auf einen halben bis einen Tag.

**Comment by seraina-silberschmidt** [comment]
LES korrekt erfassen

**Comment by seraina-silberschmidt** [comment]
Kantonale Baulinien (Dokumente + Mindestabstände)

**Comment by seraina-silberschmidt** [comment]
5921-5929 Hecken, Feldgehölze, Ufergehölze - Code 5921 fix vergeben für Hecken
5921-5929 Hecken, Feldgehölze, Ufergehölze - Code 5922 fix vergeben für Feldgehölze

**Comment by ruff-kid** [comment]
Die Dokumente zu "Anpassung Höhenstrasse West" werden zurzeit in die Planablage integriert. Bitte die Anpassungen noch nicht vornehmen bis ich die Plannummern bestätigen kann.
- Die Pläne sollen 124-61a-P heissen (gehören Inhaltich und Datumstechnisch dorthin).
- Der «Entscheid» 124-61a-E besteht aus dem Baugesuch und dem Emailverkehrt mit Ruedi Bieri. In der Planliste hat es keine RRB Nr., Datum ist der 07.05.2013

**Comment by seraina-silberschmidt** [comment]
Task erledigt / Datensatz am 28.01.2021 via Email ans ARP abgegeben

**Comment by ruff-kid** [comment]
@seraina-silberschmidt 
Bitte Entschuldige, dass ich nicht richtig auf dein Mail vom 28.01. reagiert habe. War im Validator-Update Tunnel und habe nur verstanden, dass ihr nun die Fehler findet und bereinigen könnt. Dass dies nun die überarbeite Version zu Aufschalten ist entging mir :-(
habe es soeben zum Aufschalten weitergeleitet.

**Comment by seraina-silberschmidt** [comment]
@ruff-kid Ah nein, kein Problem. Im Gegenteil: Mir ist plötzlich eingefallen, dass ich gemäss dem Nachführungsprozess die Daten auf GitHub stellen und den Projektstatus anpassen müsste...
Vielen Dank für die Weiterleitung ans AGI.
