### ISSUE TITLE
[2615] Erschwil Jermann

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#23]
Datei anpassen damit auch Version ilivalidator-1.11.3 fehlerfrei durchläuft https://geo.so.ch/ilivalidator

Bitte xtf und log-file direkt ins Github anhängen.
Wenn beendet bitte den Projects status von "Bearbeitung (Planer)" zu "Validation (ARP)" anpassen.

Um die Daten nachzuführen sind folgende Schritte zwingen einzuhalten:

- Aktuelle Daten vom Kanton herunterladen und importieren
- Daten anpassen gemäss Meldung vom Amt für Raumplanung
- Daten exportieren (INTERLIS)

**Comment by seraina-silberschmidt** [comment]
Kantonale Baulinien (Dokumente + Mindestabstände) erfassen

**Comment by seraina-silberschmidt** [comment]
LES prüfen

**Comment by seraina-silberschmidt** [comment]
Hier ist der bereinigte Datensatz: 
[erschwil_nup.zip](https://github.com/bjdarp/nplso-nf/files/6406008/erschwil_nup.zip)
