### ISSUE TITLE
[test1] Bottmingen superplaner

### ISSUE THREAD

**Issue by Ruff-ieux** [bjdarp/nplso-nf#25]
1. outlook eröffnet mit titel
2. an ruff-kid verweissen (ARP)

**Comment by ruff-kid** [comment]
1. ruff-kid mail erhalten
weiterleiten an hrhax

**Comment by hrhax** [comment]
korrigiert
ARP bitte kontrollieren

**Comment by ruff-kid** [comment]
kontrolle gut. bitte aufschalten

**Comment by Ruff-ieux** [comment]
ist freigeschaltet. schliesse nun das ticket
