### ISSUE TITLE
[074, 2454] Egerkingen BSB

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#32]

**Comment by ruff-kid** [comment]
Datei anpassen damit auch Version ilivalidator-1.11.3  fehlerfrei durchläuft https://geo.so.ch/ilivalidator

@Langenstein wenn fertig, kannst das xtf und log-file direkt ins Github anhängen? Wenns klapp können wir uns Email sparren.

Um die Daten nachzuführen sind folgende Schritte zwingen einzuhalten:

1.	Aktuelle Daten vom Kanton herunterladen und importieren
2.	Daten anpassen gemäss Meldung vom Amt für Raumplanung
3.	Daten exportieren (INTERLIS)

**Comment by Langenstein** [comment]
[npl_egerkingen.zip](https://github.com/bjdarp/nplso-nf/files/4681297/npl_egerkingen.zip)

An aktuellen Ilivalidator angepasst,

**Comment by bjsvwcur** [comment]
@ruff-kid Daten sind nachgeführt
