### ISSUE TITLE
[34, 2457]Messen LerchWeber

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#33]
In Messen gibt es Polygone, die in zwei ehemaligen Gemeinden liegen. Diese sollte man in Polygone aufschneiden/teilen. 
Das führt dazu, dass insbesondere die Dokumente falsch verknüpft sind. Auf dem ehemaligen Gemeindegebiet von Oberramsern gilt jetzt das Zonenreglement von Balm. 

![grafik](https://user-images.githubusercontent.com/56681444/77427278-65688900-6dd6-11ea-8274-29491868ee74.png)

[grundbuchkreise.zip](https://github.com/bjdarp/nplso-nf/files/4375335/grundbuchkreise.zip)

**Comment by ruff-kid** [comment]
@ruff-kid Fehler wurde gemeldet von Roland Iseli (Messen) => am Schluss wieder bei ihm melden

**Comment by adis-LW** [comment]
Ab 30.03.2020 ist Armin wieder von den Ferien zurück und wird das aktuelle XTF von Messen einbinden, damit ich den Fehler beheben kann.

**Comment by ghost** [comment]
Master von Messen 2457.XTF ist jetzt bei uns.
@adis-LW db angelegt und qgs vorbereitet.

**Comment by adis-LW** [comment]
[exp1_nplmes3_2020200331A.zip](https://github.com/bjdarp/nplso-nf/files/4407603/exp1_nplmes3_2020200331A.zip)
 
Inhalte, Dokumentverknüpfungen und publiziertAb-Daten aufgeteilt gem. Grundbuchkreisen.

**Comment by ruff-kid** [comment]
Ich habe den Fehler im Workflow gefunden. Das Projekt wurde nicht von "Bearbeitung (Planer)" zu "Validation (ARP)" verschoben. Trotzdem habe ich ein Mail erhalten, dass die Daten gespeichert wurden und ich am Zug wäre es an Sandra weiterzugeben. Mein Fehler- sry

**Comment by ghost** [comment]
Haben wir für Messen 2 threads? #33 #38? Kann man mergen?

**Comment by ruff-kid** [comment]
Änderungen werden im #38 angepasst.
