### ISSUE TITLE
[126, 2616] Fehren LerchWeber

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#37]
Gemäss Email: beim Eichenweg die Baulinien einen 3m-Abstand haben sollten gem. rechtsgültigem Erschliessungsplan (nicht 4 m, wie momentan erfasst).

**Comment by adis-LW** [comment]
[exp1_nplfeh2_20200512A.zip](https://github.com/bjdarp/nplso-nf/files/4615729/exp1_nplfeh2_20200512A.zip)
Baulinie bereinigt.

**Comment by ruff-kid** [comment]
@bjsvwcur bitte die Verbesserung aufschalten - Datei ist weiter oben angehängt.

**Comment by bjsvwcur** [comment]
@ruff-kid Die Daten sind aktualisiert
