### ISSUE TITLE
[2457] Messen LerchWeber

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#38]
https://geo.so.ch/map/?k=f38890a97 
**Messen GB-Nr. 267**

Besten Dank für ihre Rückmeldung. Die Parzelle wurde **fälschlicherweise als Verkehrszone** erfasst. Leider ist die korrekte Zuweisung nicht klar. Der Bauzonenplan lässt die Fläche weiss (keine Zonenzuweisung), der Erschliessungsplan lässt die Fläche weiss (keine Zonenzuweisung) und auch der Gesamtplan lässt die Fläche weiss (keine Zonenzuweisung, folglich auch keine Landwirtschaftszone). Unbestritten liegt die Fläche innerhalb der Bauzone.
 
Dieser Parzelle wurde keiner rechtsgültige Zonierung zugewiesen!

Nach Absprache mit der Kreisplanerin Corinne Stauffiger, werden wir es als **1691 «keine Nutzung zugewiesen»** verbessern. Zudem wird der Fläche die Bemerkung «In der Ortsplanungsrevision bereinigen» anfügen. Diese Bemerkung wird dem Datensatz direkt angehängt, damit die Erkenntnis bestimmt nicht vergessen geht. Ersichtlich sind solche Bemerkungen jedoch nur beim direkten betrachten der Daten und nicht im WebGis.

**Comment by adis-LW** [comment]
[exp1_nplmes3_2020200331A.zip](https://github.com/bjdarp/nplso-nf/files/4656662/exp1_nplmes3_2020200331A.zip)
Im ZIP ist unser aktuellstes XTF von Messen, das wir abgegeben haben.
Im ARP-Index https://geo.so.ch/geodata/ch.so.arp.nutzungsplanung/ findet man ein anderes XTF. Welches ist der Master?

**Comment by ghost** [comment]
Mail an Andrea Disler
Hoi Andrea
Würdest bitte Du im Github nachfragen, ob hier https://geo.so.ch/geodata/ch.so.arp.nutzungsplanung/ 2457.xtf aktuell ist. Unter TransferMetadaten.Datenbestand steht <Bemerkungen>**dbnplmes ;-) 20191028W ç**</Bemerkungen>.
Mit mes3 hast Du am 31.03.2020 exp1_nplmes3_2020200331A.xtf ans Arp abliefert. Unter TransferMetadaten.Datenbestand steht <Bemerkungen>**dbnplmes3 20200330Z ;-)**</Bemerkungen>.
Das deutet darauf hin, dass 2457.xtf nicht aktuell ist. Es wäre schade, wenn die mit mes3 gemachten Ergänzungen verloren gehen würden.
@Arp: Es ist **SEHR wichtig zu definieren, wo der Master ist! Wenn man an einer definierten Stelle, z.B. unter TransferMetadaten.Datenbestand eine Zeitmarke oder etwas Ähnliches erfasst, kann man das File wenigstens identifizieren (wie im obigen Fall).**
Ich lege somit die Datenbank für mes4 momentan nicht an.
Freundliche Grüsse
Armin

Mail von Stefan Ziegler
Hallo zäme
Wurde die erwähnte Datei von Armin "exp1_nplmes3_2020200331A.zip" damals importiert? In der Tabelle "arp_npl.t_ili2db_import" sehe ich nur den Import vom 11. Februar (was mit der Beobachtung von Armin übereinstimmen würde).
@Alex / @Sandra: Wie ist der Workflow? Wie weiss Sandra, dass sie etwas importieren muss? Es scheint diese Lieferung in diesem Ticket zu sein: https://github.com/bjdarp/nplso-nf/issues/33 
@Sandra: Wie importierst du die Daten? Nicht mit dem arp_npl_import GRETL-Job? 

Mail von Alex Ruff
Hallo allerseits
Ich habe den Fehler im Workflow gefunden. Das Projekt wurde nicht von "Bearbeitung (Planer)" zu "Validation (ARP)" verschoben. Trotzdem habe ich ein Mail erhalten, dass die Daten gespeichert wurden und ich am Zug wäre es an Sandra weiterzugeben. Mein Fehler- sorry
Um auf die Handlungsebene zurück zu kommen, sehe ich zwei Möglichkeiten.
A) exp1_nplmes3_2020200331A.zip aufschalten und danach kann LerchWeber das Projekt importieren, bearbeiten und uns "nplmes4.." abgeben. Würden dem tatsächlichen Sachverhalt entsprechen. Eigentlich korrektes vorgehen.
B) neue Änderungen direkt im vorhandenen Projekt bei LerchWeber integrieren und uns die beiden Änderungen in einem Datensatz abgeben. AGI müsste die Daten nur 1x aufschalten.
Spricht etwas gegen vorgehen B? Ich kann inhaltlich beides auf einmal überprüfen.
Freundliche Grüsse 
Alexander Ruff 

Mail von Andrea Lüscher
Hallo Alex
Ich würde Variante B nehmen ... für diesen speziellen Fall.
Liebe Grüsse 
Andrea Lüscher

**Comment by ghost** [comment]
LWAG wählt Variante B, für diesen Fall...

**Comment by ghost** [comment]
Haben wir für Messen 2 threads? #33 #38? Kann man mergen?

**Comment by adis-LW** [comment]
Daten von Messen sind bereinigt. Aktuelles Paket zur Validation:
[exp1_nplmes3_20200526B.zip](https://github.com/bjdarp/nplso-nf/files/4680137/exp1_nplmes3_20200526B.zip)

**Comment by bjsvwcur** [comment]
@ruff-kid Daten sind nachgeführt
