### ISSUE TITLE
[2424] Herbetswil BSB

### ISSUE THREAD

**Issue by ruff-kid** [bjdarp/nplso-nf#44]
Der Datensatz muss mit den beiden neusten Planungen ergänzt werden.

https://so.ch/fileadmin/internet/bjd/bjd-arp/Planregister/arp_plaene_68.pdf
Es handelt sich um die Pläne 68/28 und 68/29.

Anpassungen gelangen über ein Ticketsystem zum Büro und werden innert Monatsfrist bearbeitet - also bis anfang Januar.

**Comment by Langenstein** [comment]
Nachführung vorgenommen. Versand an Alex am 03.12.20
